name: My workflow
on: 
  pull_request:
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout my-organization/awesome-action
        uses: actions/checkout@v2
        with:
          repository: ahopkins/pbot
          ref: refs/heads/main
          # GitHub's personal access token with access to `my-organization/awesome-action`
          token: $
          persist-credentials: false
          path: ./
      - uses: ./
      - name: Last step
