name: My workflow
on:
  pull_request:
  push:
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Checkout ahopkins/pbot
        uses: actions/checkout@v2
        with:
          repository: ahopkins/pbot
          ref: refs/heads/main
          # GitHub's personal access token with access to `my-organization/awesome-action`
          token: ${{ secrets.AHOPKINS_PAT }}
          persist-credentials: false
          path: ./
      - uses: ./
        name: My private repo
